stages:
  - test
  - build
  - deploy

image: node:8

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - yarn install

lint:
  stage: test
  allow_failure: true
  script:
    - yarn lint

lint-critical:
  stage: test
  # allow_failure: true
  script:
    - yarn lint:critical

test:
  stage: test
  allow_failure: true
  script:
    - yarn test

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - ./build/

deploy:
  stage: deploy
  dependencies:
    - build
  only:
    - master
  script:
    - ./scripts/upload.sh ./dist/
