stages:
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

lint:
  stage: test
  tags:
    - docker
  image: node:8
  allow_failure: true
  script:
    - npm run lint

lint-critical:
  stage: test
  tags:
    - docker
  image: node:8
  # allow_failure: true
  script:
    - npm run lint:critical

test:
  stage: test
  tags:
    - docker
  image: node:8
  allow_failure: true
  script:
    - npm run test

build:
  stage: build
  tags:
    - docker
  image: node:8
  script:
    - npm run build
  artifacts:
    paths:
      - ./dist/

deploy:
  stage: deploy
  dependencies:
    - build
  tags:
    - docker
  image: kalahari/ncftp
  only:
    - master
  script:
    - ./scripts/upload.sh ./dist/
