stages:
  - test
  - build
  - deploy

image: node:8

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm run install

lint:
  stage: test
  allow_failure: true
  script:
    - npm run lint

lint-critical:
  stage: test
  # allow_failure: true
  script:
    - npm run lint:critical

test:
  stage: test
  allow_failure: true
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - ./build/

deploy:
  stage: deploy
  dependencies:
    - build
  only:
    - master
  script:
    - ./scripts/upload.sh ./dist/
