stages:
  - prepare
  - lint
  - test
  - build
  - deploy

image: node:10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules/

install:
  stage: prepare
  tags:
    - docker
  script:
    - npm install

lint:
  stage: lint
  tags:
    - docker
  before_script:
    - npm install
  script:
    - npm run lint

test:
  stage: test
  tags:
    - docker
  before_script:
    - npm install
  script:
    - npm run test

build:
  stage: build
  tags:
    - docker
  script:
    - npm run build
  artifacts:
    paths:
      - ./dist/

# deploy:
#   stage: deploy
#   dependencies:
#     - build
#   only:
#     - master
#   tags:
#     - deploy:helloworld
#   script:
#     - ./scripts/deploy.sh ./dist/

# deploy:
#   stage: deploy
#   dependencies:
#     - build
#   only:
#     - master
#   tags:
#     - docker
#   image: emiketic/essentials
#   script:
#     - ./scripts/deploy.sh ./dist/

deploy:
  stage: deploy
  dependencies:
    - build
  only:
    - master
  tags:
    - docker
  image: node:10
  script:
    - npm install -g firebase-tools
    - firebase --token $FIREBASE_TOKEN use $FIREBASE_PROJECT_ID
    - firebase --token $FIREBASE_TOKEN target:apply hosting default $FIREBASE_PROJECT_ID-vue
    - firebase --token $FIREBASE_TOKEN deploy -m "build $CI_COMMIT_REF_NAME / $CI_COMMIT_SHORT_SHA" --non-interactive
